const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

const MESSAGES = {
  LOGGED_OUT: 'Logged out',
  USER_NOT_FOUND: 'Cannot find user'
};

export { STATUS_CODES, MESSAGES };
